### ISSUE TITLE
renault-api (CLI) stopped working 9 days ago

### ISSUE THREAD

**Issue by davidweisgerber** [hacf-fr/renault-api#1160]
Since then I get the following error:
david@fourconnected:~$ /usr/local/bin/renault-api status
charge-mode: Access is denied for this resource
Traceback (most recent call last):
  File "/usr/local/bin/renault-api", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/renault_api/cli/helpers.py", line 39, in wrapper
    asyncio.run(run_command(func, *args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/renault_api/cli/helpers.py", line 30, in run_command
    await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/renault_api/cli/__main__.py", line 178, in status
    await renault_vehicle.display_status(websession, ctx_data)
  File "/usr/local/lib/python3.10/dist-packages/renault_api/cli/renault_vehicle.py", line 159, in display_status
    await update_cockpit(vehicle, status_table, ctx_data)
  File "/usr/local/lib/python3.10/dist-packages/renault_api/cli/renault_vehicle.py", line 267, in update_cockpit
    ("Total mileage", response.totalMileage, "km"),
AttributeError: 'NoneType' object has no attribute 'totalMileage'

**Comment by epenet** [comment]
Fixed in 0.2.2

**Comment by davidweisgerber** [comment]
Thank you very much for your quick reply. When will release 0.2.2 be available through pip?

**Comment by davidweisgerber** [comment]
Thank you very much!
