### ISSUE TITLE
HVAC Start not working (Zoe50)

### ISSUE THREAD

**Issue by ianthommo** [hacf-fr/renault-api#1330]
I'm using the CLI and most functions work but HVAC Start keeps failing. Used to work back in July. I'm updated to version 2.7 but also fails with 2.3 (which used to work!). Also an error on 'log status' but I still get a result. I've reset all the keys etc so am now stuck! 
Thanks for any help

Here are the examples
 renault-api --log status
lock status: {"errors":[{"errorCode":404,"errorMessage":"There is no data for this vin and uid","errorLevel":"error","errorType":"functional"}],"error_reference":"rrt-0e76a296e56599dae-c-eu-15751-174272968-9"}
res state: The access is forbidden
----------------  -------------------------
Battery level     63 %
Last updated      2024-09-29 17:30:32
Range estimate    177 km
Plug state        PlugState.UNPLUGGED
Charging state    ChargeState.NOT_IN_CHARGE
Time remaining    20 min
Charge mode       schedule_mode
Total mileage     36791.0 km
Fuel autonomy     0.0 km
Fuel quantity     0.0 L
GPS Latitude      51.40441
GPS Longitude     0.05402861111111111
GPS last updated  2024-09-21 17:31:31
HVAC status       off
----------------  -------------------------
 $ renault-api hvac start --temperature 20
Traceback (most recent call last):
  File "/home/ian/.local/bin/renault-api", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.11/site-packages/renault_api/cli/helpers.py", line 39, in wrapper
    asyncio.run(run_command(func, *args, **kwargs))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ian/.local/lib/python3.11/site-packages/renault_api/cli/helpers.py", line 30, in run_command
    await func(*args, **kwargs)
  File "/home/ian/.local/lib/python3.11/site-packages/renault_api/cli/hvac/control.py", line 44, in start
    click.echo(response.raw_data)
               ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'raw_data'

**Comment by zefir-o** [comment]
I'm getting nearly the same result.
renault-api --log status
lock status: {"errors":[{"errorCode":404,"errorMessage":"There is no data for this vin and uid","errorLevel":"error","errorType":"functional"}],"error_reference":"..."}
res state: The access is forbidden

Any progress on this issue so far?

**Comment by epenet** [comment]
"lock status" and "res state" are not available on all vehicle - so this is normal

**Comment by epenet** [comment]
@ianthommo / @zefir-o can you please confirm your vehicle model-code?
