### ISSUE TITLE
CLI exception on json list response

### ISSUE THREAD

**Issue by FRSTR** [hacf-fr/renault-api#512]
When using CLI (e.g. renault-api --debug http get) and trying to obtain response for notification endpoint (/commerce/v1/persons/somePersonIdHere/notifications/kmr?&notificationId=someIdHere), the response fires an exception.

Example response, which appears to be a list, and that fact is probably the cause of the exception below.
```
[{"notificationId":"12364643-67aa-4bc5-1ea4-14272f281ad6","notifDate":"2022-02-01T19:01:51.622","vin":"V1LHABC5500112233","personId":"32364643-67aa-4bc5-1ea4-14272f281ad6","kmrUserId":"12345","actionType":"COMMAND_RESPONSE","commandResponse":{"status":"CREATED"},"commandType":"SRP_SETS"},
{"notificationId":"12364643-67aa-4bc5-1ea4-14272f281ad6","notifDate":"2022-02-01T19:01:51.623","vin":"V1LHABC5500112233","personId":"32364643-67aa-4bc5-1ea4-14272f281ad6","kmrUserId":"12345","actionType":"SRP_SALT_REQUEST","srpResponse":{"status":"OK","loginB":"CBC3E2329FC4004AC599D5FC209648F","loginSalt":"654"}}]
```
Exception output:
```
Traceback (most recent call last):
  File "/home/frstr/.local/bin/renault-api", line 11, in <module>
    sys.exit(main())
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frstr/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/cli/helpers.py", line 39, in wrapper
    asyncio.run(run_command(func, *args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/cli/helpers.py", line 30, in run_command
    await func(*args, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/cli/__main__.py", line 234, in http_get
    await renault_client.http_request(websession, ctx_data, "GET", endpoint)
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/cli/renault_client.py", line 158, in http_request
    response = await session.http_request(method, endpoint, json_body)
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/renault_session.py", line 170, in http_request
    json=json,
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/kamereon/__init__.py", line 143, in request
    kamereon_response: models.KamereonResponse = schema.loads(response_text)
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow/schema.py", line 753, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 639, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow/schema.py", line 720, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow/schema.py", line 845, in _do_load
    PRE_LOAD, data, many=many, original_data=data, partial=partial
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow/schema.py", line 1096, in _invoke_load_processors
    partial=partial,
  File "/home/frstr/.local/lib/python3.7/site-packages/marshmallow/schema.py", line 1220, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/home/frstr/.local/lib/python3.7/site-packages/renault_api/models.py", line 27, in get_raw_data
    return {"raw_data": data, **data}
TypeError: 'list' object is not a mapping
```

**Comment by epenet** [comment]
I suggest that you obfuscate the personal data, and add a fixture to replicate the issue in tests

**Comment by FRSTR** [comment]
The example here is already obfuscated, but where should this fixture be added? 
Plus sometimes there is only 1 item in the list, it probably worth adding a second fixture for that option in that case too .

**Comment by epenet** [comment]
Needs to be in `tests/fixtures/kamereon/...`
Maybe `tests/fixtures/kamereon/person/notifications.1.json`
