### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by bruvv** [hacf-fr/renault-api#545]
When using the API in home assistant there is an error trown. Can you have a look at it?

```
2022-03-08 14:54:50 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 502 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/redacted/kamereon/kca/car-adapter/v2/cars/redacted/battery-status?country=NL: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

2022-03-08 14:54:50 ERROR (MainThread) [homeassistant.components.renault.renault_vehicle] Unexpected error fetching redacted battery data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/renault/renault_coordinator.py", line 50, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_vehicle.py", line 131, in get_battery_status
    response = await self.session.get_vehicle_data(
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_session.py", line 221, in get_vehicle_data
    return await kamereon.get_vehicle_data(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 298, in get_vehicle_data
    await request(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 149, in request
    kamereon_response: models.KamereonResponse = schema.loads(response_text)
  File "/usr/local/lib/python3.9/site-packages/marshmallow/schema.py", line 752, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bruvv** [comment]
Still an issue @epenet

**Comment by bruvv** [comment]
Closing because of this: https://github.com/hacf-fr/renault-api/pull/569
