### ISSUE TITLE
Not working on home assistant anymore 

### ISSUE THREAD

**Issue by bruvv** [hacf-fr/renault-api#623]
First it happened that sometimes after a restart of home assistant the API was picked up again. Now it doesn't work anymore. Sometimes the error is as follows:

```
Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/renault/__init__.py", line 28, in async_setup_entry await renault_hub.async_initialise(config_entry) File "/usr/src/homeassistant/homeassistant/components/renault/renault_hub.py", line 62, in async_initialise await asyncio.gather( File "/usr/src/homeassistant/homeassistant/components/renault/renault_hub.py", line 85, in async_initialise_vehicle assert vehicle_link.vehicleDetails is not None AssertionError
```

**Comment by epenet** [comment]
This is not an error with the renault-api, but with the way Home Assistant expects some data that is no longer provided by Renault.
The Home Assistant component needs to be tweaked accordingly.

**Comment by PacDeSaintes** [comment]
Problem solved

**Comment by bruvv** [comment]
I can confirm. This was a fuck up from Renault and they fixed their end points... Stupid company.
